### ISSUE TITLE
Wrong executable file on master branch

### ISSUE THREAD

**Issue by choiking10** [fraunhoferhhi/omaf.js#13]
```
omaf.js/omaf-file-creation/createTestVectors/bin/linux$ file TApp360Convert 
TApp360Convert: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=a17847bb4a597a4d182593300ef3b1228ecf0d9d, not stripped
omaf.js/omaf-file-creation/createTestVectors/bin/linux$ file TAppEncoder 
TAppEncoder: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=c2fdc9771d382a0003f7e829f04a87f7e4486551, not stripped
omaf.js/omaf-file-creation/createTestVectors/bin/linux$ file hevc2omaf 
hevc2omaf: Mach-O 64-bit x86_64 executable
```
When I run the create_omaf_files.py script on the master branch, I encountered an error. I checked and found that the hevc2omaf file is a binary for mac. But, hevc2omaf of edgebrowser branch is a linux binary.

**Comment by podborski** [comment]
Looks like you are trying to run it on 32 bit system. Those binaries are compiled for 64 bit. Can you execute `uname -a` and post its output here?

**Comment by choiking10** [comment]
@podborski  
```
Linux 4.15.0-64-generic #73~16.04.1-Ubuntu SMP Fri Sep 13 09:56:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
```
But, as far as I know, we can read file's information as `file hevc2omaf` command.

File command printed 'Mach-O 64-bit x86_64 executable', as far as I understood, it means this executable is for Mac OS. 

And when I ran that executable on the mac, it worked properly.

**Comment by podborski** [comment]
You are right. macOS build was copied to linux folder. We will fix it. Thank you for pointing to it.

You can check out 69c0908960efe43dedf0ac2d6fc84ece12193088 for hevc2omaf. This will work. The updates we did after that are related to 3GPP Advanced media profile only
