### ISSUE TITLE
How to resolve error "This browser does not support the following mimetype"?

### ISSUE THREAD

**Issue by peipeiguo** [fraunhoferhhi/omaf.js#16]
Hi all,

I want to run omaf.js on my PC, but got below error, any one who know how to resolve it? 
My env is: Win 7 + Microsoft Edge 79.0.309.15.  (I switched to edgebrowser branch, still error.)
And same error on Win 7 + Chrome 78.0.3904.108.

> This browser does not support the following mimetype
> mimiType: video/mp4; codecs="hvc1.1.6.L153.80"
> Please use another browser.

![image](https://user-images.githubusercontent.com/11475326/70596121-111f0c00-1c20-11ea-843e-d3f61646d6d8.png)

Thanks.

**Comment by JWSon** [comment]
Hello @peipeiguo ,

Thank you for your comment.
Regarding mimetype on winOS, we discussed that on #8.

**Comment by podborski** [comment]
Hi @peipeiguo, HEVC support on browsers other than Safari might be tricky. 

Are you able to play any "normal" (non-omaf) HEVC video in your browser? If yes, then it might be our issue.

I remember that Edge browser when running on the device with a Hardware HEVC decoder (for example Surface book) was able to play HEVC while on desktop PC in some cases it was required to install [HEVC Video Extensions](https://www.microsoft.com/en-us/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq?activetab=pivot:overviewtab) from the Microsoft Store. However I'm not sure what the current status of HEVC support in Edge is.

Microsoft is currently working on new version of Edge (which will be based on Chromium). I believe there was already some beta release of it available. So things might change a bit soon.

**Comment by peipeiguo** [comment]
Hi @JWSon @podborski, 

Finaly, I switched to Win 10 PC and downloaded [Microsoft Edge Dev version](https://www.microsoftedgeinsider.com/en-us/download). Then it works. Great OMAF player!

Thanks for your kindly help.

**Comment by podborski** [comment]
@peipeiguo great 😄 

I didn't test it with the new beta of the edge. But it might also work on the main branch? Because the edge branch was created as a hack for the old version of edge. It can not switch video tracks based on the viewport.

**Comment by zzy139** [comment]
@peipeiguo hi 
I tried your solution ,but it didn't work
(-->   I switched to Win 10 PC, downloaded Microsoft Edge Dev version and installed HEVC Video Extensions (it is only for Win 10) you mentioned.)
Can it still work now？
