### ISSUE TITLE
Valid zip file?

### ISSUE THREAD

**Issue by mrajiullah** [fraunhoferhhi/omaf.js#18]
Hi!

Is the following resource still valid 
curl https://datacloud.hhi.fraunhofer.de/nextcloud/s/38tHKMQTogibTKM/download -o content.zip 

My unzipped says the zip file is not valid.

Thanks,
M

**Comment by podborski** [comment]
I guess my shared folder is now not available anymore since I'm not working for HHI anymore. @JWSon could you provide a new link?

**Comment by JWSon** [comment]
Hi :)
I've updated the link and you can download the file.

Best,
Jangwoo

**Comment by mrajiullah** [comment]
Hi!

Could I also get the updated link here
Otherwise the old link is not working

```
$ curl https://datacloud.hhi.fraunhofer.de/nextcloud/s/38tHKMQTogibTKM/download -o content.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0$ curl 
```

Thanks,
M

**Comment by JWSon** [comment]
the link is https://datacloud.hhi.fraunhofer.de/s/yojnrKZqWmmWCwy/download

Best,
Jangwoo

**Comment by mrajiullah** [comment]
Thanks!

**Comment by mrajiullah** [comment]
Hi!

Again!
Is it ok if I put this content in some publicly accessible server.

Best,
M

On 30 Nov 2020, at 21:42, Jangwoo Son <notifications@github.com<mailto:notifications@github.com>> wrote:

https://datacloud.hhi.fraunhofer.de/s/yojnrKZqWmmWCwy/download

**Comment by JWSon** [comment]
Currently, the test content is open to the public only for testing purpose on the OMAF.JS. Please refrain from upload to other public servers.
Instead, it would be a good option to refer our GitHub link :)

Best,
Jangwoo

**Comment by mrajiullah** [comment]
Yes, only for testing the omaf.js

Thanks,
M

On 1 Dec 2020, at 09:59, Jangwoo Son <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently, the test content is open to the public only for testing purpose on the OMAF.JS. Please refrain from upload to other public servers.
Instead, it would be a good option to refer our GitHub link :)

Best,
Jangwoo
