### ISSUE TITLE
About the division of tiles

### ISSUE THREAD

**Issue by HaoranLv** [fraunhoferhhi/omaf.js#9]
Can OMAF content in this project be cut into any number of tiles? Still can only be cut into 24?

**Comment by gurdep** [comment]
Hi @HaoranLv,
Thanks for your comment. 

The current version of [omaf-file-creator](https://github.com/fraunhoferhhi/omaf.js/tree/master/omaf-file-creation) is capable of generating OMAF-complaint files for twenty-four tiles. However, flexibility in [omaf-file-creator](https://github.com/fraunhoferhhi/omaf.js/tree/master/omaf-file-creation) may be expected in the future releases. 

Cheers,
Gurdeep

**Comment by gurdep** [comment]
Hi @HaoranLv,
Thanks for your comment. 

The current version of [omaf-file-creator](https://github.com/fraunhoferhhi/omaf.js/tree/master/omaf-file-creation) is capable of generating OMAF-complaint files for twenty-four tiles. However, flexibility in [omaf-file-creator](https://github.com/fraunhoferhhi/omaf.js/tree/master/omaf-file-creation) may be expected in the future updates. 

Cheers,
Gurdeep

**Comment by gurdep** [comment]
Hi @HaoranLv,
Thanks for your comment. 

The current version of [omaf-file-creator](https://github.com/fraunhoferhhi/omaf.js/tree/master/omaf-file-creation) is capable of generating OMAF-complaint files for twenty-four tiles. However, flexibility in [omaf-file-creator](https://github.com/fraunhoferhhi/omaf.js/tree/master/omaf-file-creation) may be expected in the future updates. 

Cheers,
Gurdeep
